/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

repositories {
  mavenCentral()
  google()
  maven {
    url = uri("https://jitpack.io/")
  }
  maven {
    url = uri("https://repo.opencollab.dev/maven-releases/")
  }
  maven {
    url = uri("https://repo.opencollab.dev/maven-snapshots/")
  }
  maven {
    url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
  }
}

plugins {
  `java-library`
  id("application")
}

application {
  mainClass.set("com.aoirint.mc_migration_tool_resources_generator_geyser.Main")
}

dependencies {
  implementation("org.geysermc:api:2.1.0-20230122.182746-86")
  implementation("org.geysermc.geyser:common:2.1.0-20230122.182756-71")
  implementation("org.geysermc.geyser:api:2.1.0-20230122.182748-86")
  implementation("org.geysermc.geyser:core:2.1.0-20230122.182759-86")
}
