/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

repositories {
  mavenCentral()
  google()
  maven {
    url = uri("https://jitpack.io/")
  }
  maven {
    url = uri("https://repo.opencollab.dev/maven-releases/")
  }
  maven {
    url = uri("https://repo.opencollab.dev/maven-snapshots/")
  }
  maven {
    url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
  }
}

plugins {
  `java-library`
  id("application")
  id("net.ltgt.errorprone") version "3.0.1"
  id("com.github.spotbugs") version "5.0.13"
}

application {
  mainClass.set("com.aoirint.mc_migration_tool_resources_generator_geyser.Main")
}

dependencies {
  implementation("org.geysermc.geyser:core:2.1.0-20230202.213610-91") { isTransitive = false }
  implementation("commons-cli:commons-cli:1.5.0")
  implementation("org.apache.commons:commons-csv:1.10.0")
  errorprone("com.google.errorprone:error_prone_core:2.18.0")
  spotbugsPlugins("com.mebigfatguy.sb-contrib:sb-contrib:7.4.7")
}
